### ISSUE TITLE
bug: UTF-8 Encoding Issue in writeFileSync Method

### ISSUE THREAD

**Issue by MayiVT** [zonary123/CobbleSTS#1]
Currently, UTF-8 encoding is not correctly applied when writing files using the `writeFileSync` method in `Utils.java`. This may be due to a missing explicit UTF-8 encoding configuration in the `FileWriter` constructor.

To resolve this, I've added `StandardCharsets.UTF_8` to the `FileWriter` in the `writeFileSync` method, ensuring consistent UTF-8 encoding across file operations. This change matches the encoding setup already applied to the file reading method, which does not require updates. (Needs to be tested though, my computer is not liking to compile java files today)

### Files affected:
`common/src/main/java/com/kingpixel/cobblests/utils/Utils.java`

**Comment by zonary123** [comment]
I'm working on an update to CobbleSTS to link it with CobbleUtils. Thanks for the fix, but in the next version, the Utils from CobbleSTS will be removed since I’m using the one from CobbleUtils, where this issue is already fixed. There will also be more features and improvements for CobbleUtils.
